export enum ViewsEnum {
	UNAUTHORIZED = 'UNAUTHORIZED',
	HOME_VIEW = 'HOME_VIEW',

	WISLA_PLOCK_SINGULAR_FORM_VIEW = 'WISLA_PLOCK_SINGULAR_FORM_VIEW',
	WISLA_PLOCK_MULTIPLE_FORM_VIEW = 'WISLA_PLOCK_MULTIPLE_FORM_VIEW',

	TEST = 'TEST'
}
